# Generated by Django 3.2.5 on 2022-06-14 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_app', '0009_auto_20220607_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 14, 19, 28, 21, 291114, tzinfo=utc))),
                ('time', models.TimeField(default=datetime.datetime(2022, 6, 14, 19, 28, 21, 292108, tzinfo=utc))),
                ('req_speciality', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.doctor')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='basic_app.patient')),
            ],
        ),
    ]
