# Generated by Django 3.2.5 on 2022-06-15 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20220615_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 15)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='starttime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
