# Generated by Django 3.2.5 on 2022-06-15 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20220615_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 16)),
        ),
    ]
