# Generated by Django 3.2.5 on 2022-06-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
